title: 'Turing Talent'
default_lang: en
author:
  name: Christina
  email: christina@turingtalent.io
metadata:
  description: 'Turing Talent enables you to build world class distributed technical teams, by providing hussle-free talent sourcing, operations, managed offices, learning and development.'
  title: 'Turing Talent'    
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
